// Generated by CoffeeScript 1.12.3

/*
 * Bubble sort function.
 * This is one of the easiest sorting algorithms to implement.
 */

(function() {
  var bubbleSort, compare, swap;

  swap = function(arr, a, b) {
    var tmp;
    tmp = arr[a];
    arr[a] = arr[b];
    return arr[b] = tmp;
  };

  compare = function(a, b) {
    return a - b;
  };

  bubbleSort = function(arr, cmp) {
    var i, j, k, l, ref, ref1;
    if (cmp == null) {
      cmp = compare;
    }
    for (i = k = 0, ref = arr.length; 0 <= ref ? k < ref : k > ref; i = 0 <= ref ? ++k : --k) {
      for (j = l = ref1 = i; ref1 <= 0 ? l < 0 : l > 0; j = ref1 <= 0 ? ++l : --l) {
        if (cmp(arr[j], arr[j - 1]) < 0) {
          swap(arr, j, j - 1);
        }
      }
    }
    return arr;
  };

  if (typeof module === 'object' && module.exports) {
    module.exports = bubbleSort;
  } else if (window) {
    window.bubbleSort = bubbleSort;
  } else if (typeof define === 'function' && define.amd) {
    define([], function() {
      return bubbleSort;
    });
  }

}).call(this);
