// Generated by CoffeeScript 1.12.3

/*
 * Sorting algorithms
 */

(function() {
  var array, bubbleSort, i, j, ref;

  bubbleSort = require('./bubblesort.js');

  array = Array(100);

  for (i = j = 0, ref = array.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
    array[i] = Math.random();
  }

  bubbleSort(array);

  console.log(array.slice(0, 5));

}).call(this);
