// Generated by CoffeeScript 1.12.3

/*
 * Here is the Leibniz formula for pi
 * https://en.wikipedia.org/wiki/Leibniz_formula_for_%CF%80
 * 
 * This formula is very simple, but takes a long time to come up with
 * an accurate number. It also occasionally includes wrong numbers after the point
 * where it should have them right.
 */

(function() {
  var leibniz, math;

  math = require('mathjs');

  math.config({
    number: 'BigNumber',
    precision: 1000
  });

  leibniz = function(n) {
    var i, j, ref, res;
    res = math["eval"]('0');
    for (i = j = 0, ref = n; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      res = math.add(res, math["eval"]("(-1)^(" + i + ") / (2 * " + i + " + 1)"));
    }
    return math["eval"]("4 * " + res);
  };

  if (typeof module === 'object' && module.exports) {
    module.exports = leibniz;
  } else if (window) {
    window.leibniz = leibniz;
  } else if (typeof define === 'function' && define.amd) {
    define([], function() {
      return leibniz;
    });
  }

}).call(this);
